# Generated by Django 2.0.1 on 2019-03-06 06:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_user', models.CharField(max_length=50)),
                ('to_user', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=1000)),
                ('current_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
