# Generated by Django 2.0.1 on 2019-03-06 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsave',
            name='user_type',
            field=models.BooleanField(default=False),
        ),
    ]
