name: Remedi
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^4.0.1
  cloud_firestore:
  firebase_auth: 0.8.1+4
  google_maps_flutter:
  flutter_map: 
  google_sign_in:
  firebase_core:
  firebase_analytics:
  rxdart:
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: 


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons:
flutter_icons:
  image_path: "images/ico.png"
  android: true
  ios: true


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  fonts:
    - family: SegoeUI
      fonts: 
        - asset: fonts/SegoeUI.ttf
        - asset: fonts/SegoeUI-Bold.ttf
        - asset: fonts/SegoeUI-Italic.ttf
          style: italic
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico.ttf
    - family: Quicksand
      fonts:
        - asset: assets/Quicksand.ttf
        - asset: assets/Quicksand-Bold.ttf
        - asset: assets/Quicksand-Light.ttf
        - asset: assets/Quicksand-Medium.ttf

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - images/facebook.png
    - images/google-plus.png
    - assets/apple.jpg
    - assets/cepthalexin.jpg
    - assets/chatbot.png
    - assets/drugs.png
    - assets/health.jpg
    - assets/interact.jpg
    - assets/paracetamol.jpg
    

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
  