# Generated by Django 2.2.7 on 2019-11-29 02:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('station_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('station_name', models.CharField(max_length=30)),
                ('manager', models.CharField(default='', max_length=10)),
                ('assistant_manager', models.CharField(default='', max_length=10)),
                ('rpf', models.CharField(default='', max_length=10)),
                ('deputy_rpf', models.CharField(default='', max_length=10)),
                ('head_officer', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('train_no', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('train_name', models.CharField(max_length=100)),
                ('run_days', models.CharField(max_length=100)),
                ('classes', models.CharField(max_length=20)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='train_destination', to='website.Station')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='train_source', to='website.Station')),
            ],
        ),
        migrations.CreateModel(
            name='TrainSeatChart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_ac', models.IntegerField(default=0, verbose_name='1st AC')),
                ('second_ac', models.IntegerField(default=0, verbose_name='2nd AC')),
                ('third_ac', models.IntegerField(default=0, verbose_name='3rd AC')),
                ('sleeper', models.IntegerField(default=0)),
                ('journey_date', models.DateField()),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Train')),
            ],
        ),
        migrations.CreateModel(
            name='TrainSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival', models.TimeField()),
                ('departure', models.TimeField()),
                ('distance', models.IntegerField()),
                ('day', models.IntegerField(default=0)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Station')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Train')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('pnr', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('transaction_id', models.CharField(max_length=20)),
                ('journey_date', models.DateField()),
                ('class_type', models.CharField(choices=[('1A', '1A'), ('2A', '2A'), ('3A', '3A'), ('SL', 'SL')], max_length=2)),
                ('transaction_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('booked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ticket_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_from', to='website.Station')),
                ('ticket_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_to', to='website.Station')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Train')),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others/Not Specified')], max_length=1)),
                ('seat_no', models.IntegerField()),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Ticket')),
            ],
        ),
    ]
