# Generated by Django 2.1.1 on 2018-11-26 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='shop_name',
            new_name='shop_id',
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_no',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
