# Generated by Django 2.1.1 on 2018-11-26 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20181126_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='shop_id',
            field=models.IntegerField(default=0),
        ),
    ]
