# Generated by Django 2.0.13 on 2019-03-04 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paytm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paytmhistory',
            name='user',
            field=models.CharField(max_length=50, verbose_name='user'),
        ),
    ]
