# Generated by Django 2.1.1 on 2018-11-07 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avail',
            fields=[
                ('med_id', models.IntegerField(primary_key=True, serialize=False)),
                ('shop_id', models.IntegerField()),
                ('units', models.IntegerField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('mfg_date', models.DateField(blank=True, null=True)),
                ('exp_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'avail',
            },
        ),
        migrations.CreateModel(
            name='ComName',
            fields=[
                ('company_name', models.CharField(blank=True, max_length=64, null=True)),
                ('custom_name', models.CharField(max_length=64, primary_key=True, serialize=False)),
            ],
            options={
                'managed': False,
                'db_table': 'com_name',
            },
        ),
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('med_id', models.IntegerField(primary_key=True, serialize=False)),
                ('shop_id', models.IntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'extra',
            },
        ),
        migrations.CreateModel(
            name='MedInfo',
            fields=[
                ('med_id', models.AutoField(primary_key=True, serialize=False)),
                ('gen_name', models.CharField(blank=True, max_length=64, null=True, unique=True)),
            ],
            options={
                'managed': False,
                'db_table': 'med_info',
            },
        ),
    ]
