# Generated by Django 2.0.1 on 2019-03-06 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_order_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='roomno',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='hostel',
        ),
    ]
