# Generated by Django 2.0.1 on 2019-03-06 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='idcard',
        ),
        migrations.RemoveField(
            model_name='usersave',
            name='idcard',
        ),
        migrations.AddField(
            model_name='doctor',
            name='is_doctor',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usersave',
            name='is_doctor',
            field=models.BooleanField(default=False),
        ),
    ]
