# Generated by Django 2.0.1 on 2019-03-06 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20190306_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersave',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
