# Generated by Django 2.0.1 on 2019-03-07 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_usersave_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='profile_photo',
        ),
    ]
