# Generated by Django 2.0.1 on 2019-03-09 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='is_online',
        ),
        migrations.RemoveField(
            model_name='usersave',
            name='is_online',
        ),
    ]
