# Generated by Django 2.2.6 on 2019-11-12 21:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0002_blog_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 12, 21, 39, 9, 45042)),
        ),
    ]
