# Generated by Django 2.2.6 on 2019-11-12 21:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0004_auto_20191112_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 12, 21, 40, 57, 540849)),
        ),
    ]
