# Generated by Django 2.2.6 on 2019-11-12 23:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogger', '0007_votes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='votes',
            new_name='vote',
        ),
    ]
